name: Release

run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [ created ]

jobs:
  validate-version:
    name: Validate Version

    runs-on: ubuntu-latest

    outputs:
      my_variable: ${{ steps.set_version.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Wait for pyngrok on PyPI
        run: VERSION=${GITHUB_REF#refs/tags/} ./scripts/wait-for-pypi.sh

  release:
    name: Release
    needs: [validate-version]
    
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${GITHUB_REF#refs/tags/}
      publish: true
