name: Release

run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [ created ]

jobs:
  wait-for-pypi:
    name: Wait for pyngrok on PyPI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Wait for pyngrok on PyPI
        run: VERSION=${GITHUB_REF#refs/tags/} ./scripts/wait-for-pypi.sh

  release:
    name: Release
    needs: [wait-for-pypi]
    
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${GITHUB_REF#refs/tags/}
      publish: true
