name: Release

run-name: Release ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
# TODO: no tagging for now, while we're just building WIPs
#   release:
#     types: [ created ]

jobs:
  build:
    name: Build

    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: make build
      - name: Docker publish
        run: make publish
