name: Release

run-name: Release ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
# TODO: no tagging for now, while we're just building WIPs
#   release:
#     types: [ created ]

jobs:
  build:
    name: Build

    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      PUBLISH: ${{ inputs.PUBLISH }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Trigger build with publish
        uses: ./.github/workflows/build.yml@main
          with:
            PUBLISH: True