name: Release

run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [ created ]

jobs:
  release:
    name: Release
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      publish: true
