name: Release

run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [ created ]

jobs:
  validate:
    name: Validate

    runs-on: ubuntu-latest

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      PLATFORM: linux/amd64

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Wait for PyPI
        run: VERSION=${GITHUB_REF#refs/tags/} ./scripts/wait-for-pypi.sh
      - name: Test downstream
        run: make build test-downstream

  release:
    name: Release
    needs: [validate]
    
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${GITHUB_REF#refs/tags/}
      publish: true
